### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by YurchukV** [quanghits/GoogleMobileAds#1]
Hello tell me how you can use Firebase Analytics with this SDK
SPM

**Comment by quanghits** [comment]
I don't know what do you say? 

it is fully compatible with firebase. Thank you!

**Comment by quanghits** [comment]
> Hello tell me how you can use Firebase Analytics with this SDK
> SPM

I don't know what do you say?

it is fully compatible with firebase. Thank you!
